name: car_expo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.2
  page_transition: ^2.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon_app.png"
  adaptive_icon_background: "#FFFFFF"
